accounts/templates/accounts/authenticate/authenticate/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

posts/urls.py
#POSTS urls.py

from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<str:pk>', views.PostDetail.as_view(), name='single'),
    path('delete/<str:pk>', views.DeletePost.as_view(), name='delete'),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.IndexPageView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('welcome/', views.WelcomePage.as_view(), name='welcome'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>SpaceBook</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/master.css' %}">

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}">SpaceBook</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link active" href="{% url 'posts:create' %}">Post</a>
            <a class="nav-item nav-link active" href="{% url 'groups:all' %}">Groups</a>
            <a class="nav-item nav-link active" href="{% url 'groups:create' %}">Create Group</a>
            <a class="nav-item nav-link active" href="{% url 'accounts:logout' %}">Log Out</a>
          {% else %}
            <a class="nav-item nav-link active" href="{% url 'accounts:signup' %}">Sign Up</a>
            <a class="nav-item nav-link active" href="{% url 'accounts:login' %}">Log In</a>
          {% endif %}

        </div>
      </div>
    </nav>


    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>


  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container jumbotron" align='center'>
  <h1>Welcome to the Space!</h1>

</div>



{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}

<h1>Thanks for visiting.</h1>

{% endblock %}

templates/welcome.html
{% extends 'base.html' %}

{% block content %}

<h1>Hi, you are now logged in.</h1>

{% endblock %}